# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tripsense
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: tripsense
service: trip-sense

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  timeout: 60
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    JWT_SECRET: ${env:JWT_SECRET}
    USERS_TABLE: ${env:USERS_TABLE}
  apiGateway:
    role:
      arn: arn:aws:iam::account-id:role/serverlessApiGatewayCloudWatchRole

functions:
  # ---------- Auth Functions ----------
  register:
    handler: src/handlers/authHandler.register
    events:
      - http:
          path: register
          method: post

  login:
    handler: src/handlers/authHandler.login
    events:
      - http:
          path: login
          method: post

  health:
    handler: src/handlers/authHandler.health
    events:
      - http:
          path: health
          method: get

  # ---------- Chat Function ----------
  chat:
    handler: src/handlers/chatHandler.getChatResponse
    events:
      - http:
          path: chat
          method: post
# Optional: Resources section to create DynamoDB table via CloudFormation
# If you want to create a table automatically, uncomment and update accordingly
# resources:
#   Resources:
#     MyUsersTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: MyUsersTable
#         AttributeDefinitions:
#           - AttributeName: email
#             AttributeType: S
#         KeySchema:
#           - AttributeName: email
#             KeyType: HASH
#         BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
